### ISSUE TITLE
Micro opt

### ISSUE THREAD

**Issue by jancajthaml** [JurajBurian/makka#1]
Thread.sleep 100ms time in dependencies calculation with while cycle inspect

**Comment by JurajBurian** [comment]
Why, is there an reason to do it ?

**Comment by jancajthaml** [comment]
build consisting of 10 modules will sleep at least 1sec, build consisting of 20 modules at least 2secs.

Hardcoded sleep time may slow the calculation process.

Can be solved with scala.concurrent.blocking and Await if blocking is required

**Comment by JurajBurian** [comment]
Understand, you mean sleeps in makka-sbt-plugin, this sleeps just block sbt thread in processign to the time when makka - initialization or dispose is finished - there is nothing to slow calculation proccess
