### ISSUE TITLE
Opensource normative coding style violations

### ISSUE THREAD

**Issue by jancajthaml** [JurajBurian/makka#2]
Indentation is done with tabs not 2 spaces.

"The Scala language encourages a startling amount of nested scopes and logical blocks (function values and such). Do yourself a favor and don’t penalize yourself syntactically for opening up a new block. Coming from Java, this style does take a bit of getting used to, but it is well worth the effort."

Cleanup

**Comment by JurajBurian** [comment]
We use modern Editors (Idea, Eclipse) so tabs gives to us freedom, how one want to see source codes, and it is internal rule used in all projects.
