### ISSUE TITLE
Configuration transformers could be done by reflection

### ISSUE THREAD

**Issue by jancajthaml** [JurajBurian/makka#8]
implicit val cfg2String: Transformer[String] 
	implicit val cfg2Int: Transformer[Int] 
	implicit val cfg2Boolean: Transformer[Boolean] 
	implicit val cfg2Long: Transformer[Long] 
	implicit val cfg2Double: Transformer[Double]
	implicit val cfg2IntList: Transformer[List[Int]] 
	implicit val cfg2StringList: Transformer[List[String]] 
	implicit val cfg2LongList: Transformer[List[Long]] 
	implicit val cfg2DoubleList: Transformer[List[Double]] 

use import scala.reflect.runtime.universe.{typeOf, TypeTag} or https://github.com/milessabin/shapeless

to make configuration tidier and cleaner

**Comment by JurajBurian** [comment]
it is common style used in Scala, thus one have open API to introduce new Transformer
